Update rebase.yml

diff --git a/.github/workflows/rebase.yml b/.github/workflows/rebase.yml
--- a/.github/workflows/rebase.yml
+++ b/.github/workflows/rebase.yml
@@ -71,7 +71,7 @@ jobs:
             fi
             
             # Checkout the branch
-            git checkout origin/"$pr_branch" --force-with-lease || { echo "Failed to checkout $pr_branch"; exit 1; }
+            git checkout origin/"$pr_branch" || { echo "Failed to checkout $pr_branch"; exit 1; }
             echo "Checked out branch $pr_branch"
             
             # Attempt to rebase the branch
